<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <Target Name="BuildClient" BeforeTargets="PrepareForBuild" Condition="'$(SkipClientBuild)' != 'true'">
    <Exec WorkingDirectory="$(MSBuildProjectDirectory)\..\Client" Command="npm ci" />
    <Exec WorkingDirectory="$(MSBuildProjectDirectory)\..\Client" Command="npm run build" />
  </Target>

</Project>
